version: "3"

services:
  postgres-blog:
    image: postgres:latest
    ports:
      - "5442:5432"
    container_name: "blog"
    restart: always
    volumes:
      - ./data-pgsql-blog:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  data-pgsql-school-system:
